Repository buidl-labs/crypto-code-school-inside-tezos, pull requests merged in 2021-03, with the labels that each got.

#205 Magic production key added.
  src/pages/auth.js
  src/pages/tezos/customizebot.js
Labels: Priority: Critical

#211 Implement Video Modal, Landing Page Image, 404 page, Copy Link in Cryptobot single
  src/images/hero.png
  src/pages/404.js
  src/pages/tezos/claim-transaction.js
  src/pages/tezos/cryptobot/[id].js
  src/pages/tezos/index.js
  src/pages/tezos/transaction.js
Labels: enhancement

#220 Improving index page load speed
  gatsby-browser.js
  src/assets/wealth.png
  src/assets/wealth.webp
  src/html.js
  src/images/hero.webp
  src/pages/tezos/index.js
Labels: Status: Accepted

#289 Implement #212 Mobile view
  package-lock.json
  package.json
  src/components/FeatureGrid/index.js
  src/components/Footer/index.js
  src/components/Mobile/index.js
  src/components/TestimonialCard/index.js
  src/pages/404.js
  src/pages/auth.js
  src/pages/tezos/academy/index.js
  src/pages/tezos/claim-transaction.js
  src/pages/tezos/cryptobot/[id].js
  src/pages/tezos/cryptobot/index.js
  src/pages/tezos/customizebot.js
  src/pages/tezos/index.js
  src/pages/tezos/marketplace.js
  src/pages/tezos/profile.js
  src/pages/tezos/transaction.js
  tailwind.config.js
Labels: enhancement

#323 Pasting color on color picker input doesnt apply
  src/pages/tezos/customizebot.js
Labels: customizer
